var data = [
    {
        id:1,
        title:"LeetCode-001两数之和",
        content:"给定一个整数数组 nums 和一个目标值 target，请你在该数组中找出和为目标值的那 两个 整数，并返回他们的数组下标",
        avatar:"../images/avatar.jpg",
        username:"小张",
        time:"2022-09-14",
        num:"59",
        sign:"学习笔记",
        tag:["LeetCode","数据结构与算法"],
        img:"../images/about.jpeg"
    },
    {
        id:2,
        title:"关于MySQL面试100个常见问题",
        content:"本文主要受众为开发人员,所以不涉及到MySQL的服务部署等操作",
        avatar:"../images/avatar.jpg",
        username:"小张",
        time:"2020-04-06",
        num:"108",
        sign:"学习笔记",
        tag:["MySql"],
        img:"../images/about.jpeg"
    },
    {
        id:3,
        title:"Linux系统使用Yum命令安装Java环境",
        content:"Linux上安装软件，可以用yum非常方便，不需要下载解压，也不需要配置环境变量,一个指令就能完成",
        avatar:"../images/avatar.jpg",
        username:"小李",
        time:"2022-01-23",
        num:"321",
        sign:"面试整理",
        tag:["Linux"],
        img:"../images/about.jpeg"
    },
    {
        id:4,
        title:"SpringBoot项目部署云服务器详细步骤",
        content:"此篇文章将详细介绍如何将自己的SpringBoot项目部署到各大互联网公司提供的在线云解决方案,并且能从外网直接访问",
        avatar:"../images/avatar.jpg",
        username:"小刘",
        time:"2021-04-10",
        num:"76",
        sign:"教程",
        tag:["SpringBoot"],
        img:"../images/about.jpeg"
    },
    {
        id:5,
        title:"Git以及Github使用指南",
        content:"GitHub于2008年4月10日正式上线，除了Git代码仓库托管及基本的Web管理界面以外，还提供了订阅、讨论组、文本渲染、在线文件编辑器、协作图谱(报表)、代码片段分享(Gist)等功能",
        avatar:"../images/avatar.jpg",
        username:"小马",
        time:"2019-06-22",
        num:"91",sign:"教程",
        tag:["Git","Github"],
        img:"../images/about.jpeg"
    },
    {
        id:5,
        title:"Git以及Github使用指南",
        content:"GitHub于2008年4月10日正式上线，除了Git代码仓库托管及基本的Web管理界面以外，还提供了订阅、讨论组、文本渲染、在线文件编辑器、协作图谱(报表)、代码片段分享(Gist)等功能",
        avatar:"../images/avatar.jpg",
        username:"小马",
        time:"2020-06-22",
        num:"91",
        sign:"教程",
        tag:["Git","Github"],
        img:"../images/about.jpeg"
    }
]
var autherData=[
			{id:1,song:"我不是你的宋冬野",title:"“民谣很苦，吉他很贵”",content:"民谣很苦，吉他很贵；女孩很美，男孩不配。民谣很富，四海为家有些话总像鱼刺一样卡在喉咙间，进退两难，想说却难以启齿",avatar:"../images/1.webp",singer:"刘大壮",time:"2020-09-12",num:"152600",listen:"听歌",img:"../images/1.webp"},
			{id:2,song:"樱花树下的约定",title:"“待到春来九月八，马踏东京赏樱花”",content:"记得把书拿去卖了，买杯奶茶，这次是青春请的客。总有一个像明月一样的人，在你最黑暗时候，出现在你的生活中，成为你那段人生的救赎",avatar:"../images/4.webp",singer:"柯柯柯啊",time:"2020-09-12",num:"268618",listen:"听歌",img:"../images/4.webp"},
			{id:3,song:"安河桥",title:"“折一枝桥旁的挽歌，收藏一段桥上的安和”",content:"曾经我们满腔热血，渴望奔向远方，无问东西，只问初心。如今我们深夜饮酒，被子碰到一起，那是梦碎的声音",avatar:"../images/5.webp",singer:"宋冬野",time:"2020-09-12",num:"152600",listen:"听歌",img:"../images/5.webp"},
			{id:4,song:"妈妈的话",title:"“父母本是在是佛，何须千里拜灵山”",content:"世间的温柔，记得给自己的妈妈留一份。和妈妈吵架了就摸摸肚脐眼，因为那是曾经和妈妈相连的地方",avatar:"../images/2.webp",singer:"Zyboy中宇",time:"2021-12-18",num:"256402",listen:"听歌",img:"../images/2.webp"},
			{id:5,song:"山楂树之恋",title:"“世界变化不停，人潮川流不息”",content:"ABCDEFG——————A boy can do everything for girl。一个男孩能为女孩做任何事情",avatar:"../images/3.webp",singer:"程佳佳",time:"2010-04-26",num:"167864",listen:"听歌",img:"../images/3.webp"}
		]